### ISSUE TITLE
DSFファイルのタグを変更できない

### ISSUE THREAD

**Issue by jarupxx** [jarupxx/STEP_J#1]
TASCAM HiResEditorで出力したばかりのDSFファイルのタグを変更すると
DSFファイルの書き込み失敗エラーが発生する

Mp3tagで一度タグを変更してからSTEP_Jに読み込ませてください

**Comment by DJ-TOYO** [comment]
> TASCAM HiResEditorで出力したばかりのDSFファイルのタグを変更すると DSFファイルの書き込み失敗エラーが発生する
> 
> Mp3tagで一度タグを変更してからSTEP_Jに読み込ませてください

始めましてjarupxxさん
DSFプラグインの作者(DJ TOYO)です。

この件について調査したかも知れませんが、私の方で調査しましたので連絡させて頂きました。
結論から申しますとTASCAM HiResEditorの不具合（仕様解釈ミス）だと思います。
メタデータの位置が設定されているにも関わらずメタデータが無いため、DSFプラグインではID3V2ヘッダー不一致でエラーとなります。

SONYの仕様書「DSF File Format Specification」には以下のように記載があります

P.3
Pointer to Metadata chunk

If Metadata doesn’t exist, set 0. If the file has ID3v2 tag, then set the pointer to it.
ID3v2 tag should be located in the end ofthe file.

翻訳しますと以下となります。
「メタデータ(ID3V2)が存在しない場合は 0 を設定します。ファイルに ID3v2 タグがある場合は、そのファイルへのポインターを設定します。
ID3v2 タグはファイルの末尾に配置する必要があります。」

しかしTASCAM HiResEditorで出力したDSFファイルのPointer to Metadata chunkには出力したファイルサイズが設定されメタデータであるID3 V2が存在しません。
存在しない場合は以上の仕様から0を設定しなければなりません。

TASCAMに連絡は必要ですが、それはそれとしましてSTEP_Jで救済処置がないか模索しまして以下のように検討しました。
・SAVEにおいてPointer to Metadata chunkが自分のファイルサイズ以上だった場合は強制書込みを行う。
・タグ削除においてDSFファイルはファイル後尾にタグがあるので強制削除しても問題ない為、タグチェックしないで（強制）削除するようにする。

手元のソースでは修正を行い動作確認はしましたがこれによる弊害がないかまで確認は取れておりません。
GitHUBを使った事がないのですが、問題なければこちらでソースをコミット致しますが如何でしょうか？

また別件ですが、jarupxxさんがGitHUBにアップ頂いたソースの改行が0x0Aのみとなりこちらと差分不一致が発生します。
こちらでVSでコンパイルすると一部のファイルが強制的に改行が修正されて差分が発生します。
これらも全て更新してしまって良いのでしょうか？

**Comment by jarupxx** [comment]
初めましてDJ TOYOさん
jarupxxです。

調査してくださりありがとうございます。
そのような原因ならば提案してくださった救済処置で問題なさそうなのでコミットお願います。

改行コードはCR+LF(0x0D,0x0A)で管理しております。差分が発生しても大丈夫だと思いますが、DJ TOYOさんの方でForkしてgit cloneコマンドでソースを落としなおして頂けますか。この方法なら差分は発生しないようです。

**Comment by DJ-TOYO** [comment]
jarupxxさん

> 調査してくださりありがとうございます。 そのような原因ならば提案してくださった救済処置で問題なさそうなのでコミットお願います。

GitHUBが初めてでしたので苦戦しましたが、何とかforkしてコミット＆プッシュする事が出来ました。
私からはjarupxxさんのGitHUBにプッシュ出来ませんでした。
この場合jarupxxさんのGitHUBにコミットされるわけではないのですが、マージはjarupxxさんが一度私の所からクローンして手動で自分のGitにマージコミットを行うのでしょうか？
それでしたらすみませんがお願い致します。

**Comment by jarupxx** [comment]
DJ-TOYOさん
おかげさまで無事マージできました。
後ほど正式版としてリリース致します。色々とありがとうございました。

**Comment by DJ-TOYO** [comment]
jarupxxさん

> 後ほど正式版としてリリース致します。色々とありがとうございました。

いえ。DSFプラグインは私が作りましたので、こちらこそお力になれて良かったです。
DSFプラグインに関しましては、また何かありましたら出来る限りサポート致します。
またエラーメッセージでFLACをDSFに直して頂いてありがとうございます。
リリース後、しばらくして気付いたので、そのうちkobarinさんに連絡して直そうと思ってました。

話変わりますが、画像対応について検討されていますでしょうか？
まずは個人的に良く使うFLACとDSFだけでも画像の差し替え機能が実装出来たらと思いましてテスト的に実装を試みましたがうまく行かなくて放置状態です。
プラグインで画像サイズ分ヒープメモリ取得を行いSTEP本体にアドレス返却が必要だと思います。
CStringで各カラムの文字列は返却しているので、そこの構造体にCStringと同じような設計で画像クラスを実装したのですが
何故かメモリアクセスエラーとなってしまいうまく行きません。
もし画像対応をお考えでしたらサポート出来ればと思いましたが、何分このような状況で私からは何もアドバイスも出来ない状況です。

**Comment by jarupxx** [comment]
DJ-TOYOさん
以前画像対応について調べたものの理解が及ばなくて、お力になるのは難しい状況です。
実装できたらと思いますけどね。
