### ISSUE TITLE
Flac1.4.2差し替えについて

### ISSUE THREAD

**Issue by DJ-TOYO** [jarupxx/STEP_J#12]
jarupxx様
お世話になっています。

STEP_JのlibFLACですがFlac1.4.2に差し替える事が出来ました。
ビルドが通って、簡単に読み込み書き換えチェックをしただけですが、良かったら私の所からマージして採用して下さい。

**Comment by jarupxx** [comment]
@DJ-TOYO 様
お世話になっております。

libFLACの差し替えありがとうございます。
私の方でもタグの読み書き削除チェックに問題なかったので採用いたします。

**Comment by jarupxx** [comment]
[v1.04](https://github.com/jarupxx/STEP_J/releases/tag/1.04) リリース

**Comment by DJ-TOYO** [comment]
@jarupxx 様

> 私の方でもタグの読み書き削除チェックに問題なかったので採用いたします。

ありがとうございます。
無事に使えたようで良かったです。
FLACは1.4.0からCMakeによるビルド環境構築に完全移行したので、今後ソースをインポートしてビルドするのが大変になるか
も知れません。
1.4.2のCMakeのビルド方法も分かりましたので、必要でしたら連絡下さい。
では
